#! /bin/sh

# default, desktop default, and window settings
bspc config border_width             2

# default and desktop settings
bspc config window_gap               12

# global settings
bspc config split_ratio              0.52
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config focus_by_distance        true
bspc config pointer_follows_monitor  true

# monitor and desktop settings
bspc config top_padding              15

bspc monitor DVI-I-1 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 0

# rules

bspc rule --add wine desktop=^0 fullscreen=on
bspc rule --add steam desktop=^0 fullscreen=on

# startup

xcompmgr -c &
nitrogen --restore
numlockx on &
panel &
